### ISSUE TITLE
heroku-20

### ISSUE THREAD

**Issue by kruulik** [Verumex/heroku-buildpack-vips#4] opened 2020-11-25 01:10 UTC
Upgraded from heroku-18 to heroku-20 and libvips no longer working.

`Could not open library 'libvips.so.42': libMagickCore-6.Q16.so.3: cannot open shared object file: No such file or directory):`

**Comment by brian-kephart** [comment] 2020-12-03 04:35
I just came here to file the same issue. I think this happens because this buildpack caches the libvips build, so the issue is that the heroku-20 stack is using a version compiled against a different version of Ubuntu. The workaround is to specify a version of libvibs that you haven't used before to force the buildpack to compile it fresh. The ultimate fix is to update this buildpack to bust the cache and recompile when the stack changes.

**Comment by hiattp** [comment] 2020-12-11 04:51
Thanks for the issue. We are open to pull requests and/or transferring ownership of this repo, our team is unlikely to get to this as we are moving away from Heroku.

**Closed as not planned** 2023-09-06 21:05 UTC
